apiVersion: v1
kind: Service
metadata:
  name: wishilience-service
  labels:
    app: wishilience
spec:
  type: LoadBalancer
  selector:
    app: wishilience
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  sessionAffinity: None
